### ISSUE TITLE
boto error when: scrapy shell https://www.ebay.com/deals

### ISSUE THREAD

**Issue by robertodijo** [robertodijo/scrapybook#1]
Scrapy version: 
Ubuntu version:

scrapy shell https://www.ebay.com/deals gives an error. However, the command request ended with the right response.

root@dev:~/book/properties# scrapy shell https://www.ebay.com/deals
2017-09-15 08:08:16 [scrapy] INFO: Scrapy 1.0.3 started (bot: properties)
2017-09-15 08:08:16 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-09-15 08:08:16 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'properties.spiders', 'SPIDER_MODULES': ['properties.spiders'], 'LOGSTATS_INTERVAL': 0, 'BOT_NAME': 'properties'}
2017-09-15 08:08:16 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, CoreStats, SpiderState
2017-09-15 08:08:16 [boto] DEBUG: Retrieving credentials from metadata server.
2017-09-15 08:08:16 [boto] ERROR: Caught exception reading instance data
Traceback (most recent call last):
  File "/usr/local/lib/python2.7/dist-packages/boto/utils.py", line 210, in retry_url
    r = opener.open(req, timeout=timeout)
  File "/usr/lib/python2.7/urllib2.py", line 404, in open
    response = self._open(req, data)
  File "/usr/lib/python2.7/urllib2.py", line 422, in _open
    '_open', req)
  File "/usr/lib/python2.7/urllib2.py", line 382, in _call_chain
    result = func(*args)
  File "/usr/lib/python2.7/urllib2.py", line 1214, in http_open
    return self.do_open(httplib.HTTPConnection, req)
  File "/usr/lib/python2.7/urllib2.py", line 1184, in do_open
    raise URLError(err)
URLError: <urlopen error [Errno 101] Network is unreachable>
2017-09-15 08:08:16 [boto] ERROR: Unable to read instance data, giving up**
2017-09-15 08:08:16 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-09-15 08:08:16 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-09-15 08:08:16 [scrapy] INFO: Enabled item pipelines:
2017-09-15 08:08:16 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6024
2017-09-15 08:08:16 [scrapy] INFO: Spider opened
2017-09-15 08:08:17 [scrapy] DEBUG: Crawled (200) <GET https://www.ebay.com/deals> (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x7f9dbab2fb10>
[s]   item       {}
[s]   request    <GET https://www.ebay.com/deals>
[s]   response   <200 https://www.ebay.com/deals>
[s]   settings   <scrapy.settings.Settings object at 0x7f9dbab2fa90>
[s]   spider     <DefaultSpider 'default' at 0x7f9db91c40d0>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser

>>>

**Comment by robertodijo** [comment]
Found several discussion about this topic:
https://github.com/scrapy/scrapy/issues/1054

**Comment by robertodijo** [comment]
Error solve by  adding the following snippet to settings.py

```
DOWNLOAD_HANDLERS = {
	's3': None,
}
```

root@dev:~/book/properties# scrapy shell https://www.ebay.com/deals
2017-09-15 10:00:37 [scrapy] INFO: Scrapy 1.0.3 started (bot: properties)
2017-09-15 10:00:37 [scrapy] INFO: Optional features available: ssl, http11, boto
2017-09-15 10:00:37 [scrapy] INFO: Overridden settings: {'NEWSPIDER_MODULE': 'properties.spiders', 'SPIDER_MODULES': ['properties.spiders'], 'LOGSTATS_INTERVAL': 0, 'BOT_NAME': 'properties'}
2017-09-15 10:00:37 [scrapy] INFO: Enabled extensions: CloseSpider, TelnetConsole, CoreStats, SpiderState
2017-09-15 10:00:37 [scrapy] INFO: Enabled downloader middlewares: HttpAuthMiddleware, DownloadTimeoutMiddleware, UserAgentMiddleware, RetryMiddleware, DefaultHeadersMiddleware, MetaRefreshMiddleware, HttpCompressionMiddleware, RedirectMiddleware, CookiesMiddleware, ChunkedTransferMiddleware, DownloaderStats
2017-09-15 10:00:37 [scrapy] INFO: Enabled spider middlewares: HttpErrorMiddleware, OffsiteMiddleware, RefererMiddleware, UrlLengthMiddleware, DepthMiddleware
2017-09-15 10:00:37 [scrapy] INFO: Enabled item pipelines:
2017-09-15 10:00:37 [scrapy] DEBUG: Telnet console listening on 127.0.0.1:6024
2017-09-15 10:00:37 [scrapy] INFO: Spider opened
2017-09-15 10:00:38 [scrapy] DEBUG: Crawled (200) <GET https://www.ebay.com/deals> (referer: None)
[s] Available Scrapy objects:
[s]   crawler    <scrapy.crawler.Crawler object at 0x7fc86323cb10>
[s]   item       {}
[s]   request    <GET https://www.ebay.com/deals>
[s]   response   <200 https://www.ebay.com/deals>
[s]   settings   <scrapy.settings.Settings object at 0x7fc86323ca90>
[s]   spider     <DefaultSpider 'default' at 0x7fc8619e1150>
[s] Useful shortcuts:
[s]   shelp()           Shell help (print this help)
[s]   fetch(req_or_url) Fetch request (or URL) and update local objects
[s]   view(response)    View response in a browser
